import {
  AlertTriangle,
  BookOpen,
  Boxes,
  CheckCircle2,
  ChevronRight,
  CircleHelp,
  Database,
  FileCode2,
  FileText,
  Folder,
  GitBranch,
  Github,
  Home,
  LayoutDashboard,
  Link2,
  ListFilter,
  Loader2,
  Network,
  RefreshCcw,
  Search,
  ShieldCheck,
  Tag,
  Tags,
  UploadCloud,
  XCircle,
} from "lucide-react";

export const Icons = {
  alert: AlertTriangle,
  book: BookOpen,
  boxes: Boxes,
  check: CheckCircle2,
  chevron: ChevronRight,
  database: Database,
  file: FileText,
  fileCode: FileCode2,
  filter: ListFilter,
  folder: Folder,
  github: Github,
  help: CircleHelp,
  home: Home,
  link: Link2,
  loader: Loader2,
  network: Network,
  refresh: RefreshCcw,
  search: Search,
  shield: ShieldCheck,
  tag: Tag,
  tags: Tags,
  upload: UploadCloud,
  x: XCircle,
};
